<a href="https://colab.research.google.com/github/ganmingzhong/Drum-Machine/blob/main/Tutorial_3_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd
import seaborn as sns
df=pd.read_csv('train_and_test2.csv')
df.head()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

In [23]:
row,column= df.shape
row

1309

In [15]:

df.describe()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
count,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.0,1309.0,1309.0,1309.0,1309.0,...,1309.0,1309.0,1309.0,1309.000000,1309.0,1309.0,1307.000000,1309.0,1309.0,1309.000000
mean,655.000000,29.503186,33.281086,0.355997,0.498854,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.294882,0.0,0.0,1.492731,0.0,0.0,0.261268
std,378.020061,12.905241,51.741500,0.478997,1.041658,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.837836,0.0,0.0,0.814626,0.0,0.0,0.439494
min,1.000000,0.170000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.000000,0.0,0.0,0.000000,0.0,0.0,0.000000
25%,328.000000,22.000000,7.895800,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.000000,0.0,0.0,1.000000,0.0,0.0,0.000000
50%,655.000000,28.000000,14.454200,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,0.000000
75%,982.000000,35.000000,31.275000,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,1.000000
max,1309.000000,80.000000,512.329200,1.000000,8.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,1.000000

In [12]:
df.sample(10)

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
659,660,58.0,113.2750,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1202,1203,22.0,7.2250,0,0,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0
1036,1037,31.0,18.0000,0,3,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
50,51,7.0,39.6875,0,4,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1116,1117,28.0,15.2458,1,0,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0
645,646,48.0,76.7292,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
67,68,19.0,8.1583,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
218,219,32.0,76.2917,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
681,682,27.0,76.7292,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
88,89,23.0,263.0000,1,3,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1

In [14]:
df.max()

Passengerid    1309.0000
Age              80.0000
Fare            512.3292
Sex               1.0000
sibsp             8.0000
zero              0.0000
zero.1            0.0000
zero.2            0.0000
zero.3            0.0000
zero.4            0.0000
zero.5            0.0000
zero.6            0.0000
Parch             9.0000
zero.7            0.0000
zero.8            0.0000
zero.9            0.0000
zero.10           0.0000
zero.11           0.0000
zero.12           0.0000
zero.13           0.0000
zero.14           0.0000
Pclass            3.0000
zero.15           0.0000
zero.16           0.0000
Embarked          2.0000
zero.17           0.0000
zero.18           0.0000
2urvived          1.0000
dtype: float64

In [16]:
df.min()

Passengerid    1.00
Age            0.17
Fare           0.00
Sex            0.00
sibsp          0.00
zero           0.00
zero.1         0.00
zero.2         0.00
zero.3         0.00
zero.4         0.00
zero.5         0.00
zero.6         0.00
Parch          0.00
zero.7         0.00
zero.8         0.00
zero.9         0.00
zero.10        0.00
zero.11        0.00
zero.12        0.00
zero.13        0.00
zero.14        0.00
Pclass         1.00
zero.15        0.00
zero.16        0.00
Embarked       0.00
zero.17        0.00
zero.18        0.00
2urvived       0.00
dtype: float64

In [18]:
df.mean()

Passengerid    655.000000
Age             29.503186
Fare            33.281086
Sex              0.355997
sibsp            0.498854
zero             0.000000
zero.1           0.000000
zero.2           0.000000
zero.3           0.000000
zero.4           0.000000
zero.5           0.000000
zero.6           0.000000
Parch            0.385027
zero.7           0.000000
zero.8           0.000000
zero.9           0.000000
zero.10          0.000000
zero.11          0.000000
zero.12          0.000000
zero.13          0.000000
zero.14          0.000000
Pclass           2.294882
zero.15          0.000000
zero.16          0.000000
Embarked         1.492731
zero.17          0.000000
zero.18          0.000000
2urvived         0.261268
dtype: float64

In [19]:
df.std()

Passengerid    378.020061
Age             12.905241
Fare            51.741500
Sex              0.478997
sibsp            1.041658
zero             0.000000
zero.1           0.000000
zero.2           0.000000
zero.3           0.000000
zero.4           0.000000
zero.5           0.000000
zero.6           0.000000
Parch            0.865560
zero.7           0.000000
zero.8           0.000000
zero.9           0.000000
zero.10          0.000000
zero.11          0.000000
zero.12          0.000000
zero.13          0.000000
zero.14          0.000000
Pclass           0.837836
zero.15          0.000000
zero.16          0.000000
Embarked         0.814626
zero.17          0.000000
zero.18          0.000000
2urvived         0.439494
dtype: float64

In [28]:
sns.barplot(data=df,x='Sex',y=len(df.Passengerid))

AttributeError: ignored